<?php

namespace ContainerX3r9K06;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S6kIlaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._s6kIla' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._s6kIla'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ContactController::index' => ['privates', '.service_locator.WZeIXfO', 'get_ServiceLocator_WZeIXfOService', true],
            'App\\Controller\\PanierController::add' => ['privates', '.service_locator.5kysFxr', 'get_ServiceLocator_5kysFxrService', true],
            'App\\Controller\\PanierController::delete' => ['privates', '.service_locator.5kysFxr', 'get_ServiceLocator_5kysFxrService', true],
            'App\\Controller\\PanierController::index' => ['privates', '.service_locator.XoZbyHI', 'get_ServiceLocator_XoZbyHIService', true],
            'App\\Controller\\PanierController::remove' => ['privates', '.service_locator.5kysFxr', 'get_ServiceLocator_5kysFxrService', true],
            'App\\Controller\\PlatController::platDetail' => ['privates', '.service_locator.Or7hJzY', 'get_ServiceLocator_Or7hJzYService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.1Z9fEX7', 'get_ServiceLocator_1Z9fEX7Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ContactController:index' => ['privates', '.service_locator.WZeIXfO', 'get_ServiceLocator_WZeIXfOService', true],
            'App\\Controller\\PanierController:add' => ['privates', '.service_locator.5kysFxr', 'get_ServiceLocator_5kysFxrService', true],
            'App\\Controller\\PanierController:delete' => ['privates', '.service_locator.5kysFxr', 'get_ServiceLocator_5kysFxrService', true],
            'App\\Controller\\PanierController:index' => ['privates', '.service_locator.XoZbyHI', 'get_ServiceLocator_XoZbyHIService', true],
            'App\\Controller\\PanierController:remove' => ['privates', '.service_locator.5kysFxr', 'get_ServiceLocator_5kysFxrService', true],
            'App\\Controller\\PlatController:platDetail' => ['privates', '.service_locator.Or7hJzY', 'get_ServiceLocator_Or7hJzYService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.1Z9fEX7', 'get_ServiceLocator_1Z9fEX7Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ContactController::index' => '?',
            'App\\Controller\\PanierController::add' => '?',
            'App\\Controller\\PanierController::delete' => '?',
            'App\\Controller\\PanierController::index' => '?',
            'App\\Controller\\PanierController::remove' => '?',
            'App\\Controller\\PlatController::platDetail' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ContactController:index' => '?',
            'App\\Controller\\PanierController:add' => '?',
            'App\\Controller\\PanierController:delete' => '?',
            'App\\Controller\\PanierController:index' => '?',
            'App\\Controller\\PanierController:remove' => '?',
            'App\\Controller\\PlatController:platDetail' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
