<?php

namespace ContainerGfeFGnK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XoZbyHIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XoZbyHI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XoZbyHI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'plat' => ['privates', 'App\\Entity\\Plat', 'getPlatService', true],
            'platRepository' => ['privates', 'App\\Repository\\PlatRepository', 'getPlatRepositoryService', true],
        ], [
            'plat' => 'App\\Entity\\Plat',
            'platRepository' => 'App\\Repository\\PlatRepository',
        ]);
    }
}
