<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ9zlsuz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ9zlsuz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ9zlsuz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ9zlsuz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ9zlsuz\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q9zlsuz',
    'container.build_id' => '5e5c5235',
    'container.build_time' => 1688996167,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ9zlsuz');
