<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYXemTna\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYXemTna/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYXemTna.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYXemTna\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYXemTna\App_KernelDevDebugContainer([
    'container.build_hash' => 'YXemTna',
    'container.build_id' => '8903f5a8',
    'container.build_time' => 1688048528,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYXemTna');
