<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOaviQtZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOaviQtZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOaviQtZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOaviQtZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOaviQtZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'OaviQtZ',
    'container.build_id' => '4746a99d',
    'container.build_time' => 1687878217,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOaviQtZ');
