<?php

namespace ContainerQ9zlsuz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Or7hJzYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Or7hJzY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Or7hJzY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'id' => ['privates', 'App\\Entity\\Plat', 'getPlatService', true],
        ], [
            'id' => 'App\\Entity\\Plat',
        ]);
    }
}
