<?php

namespace ContainerOaviQtZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VhdgA04Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VhdgA04' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VhdgA04'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'id' => ['privates', 'App\\Entity\\Categorie', 'getCategorieService', true],
        ], [
            'id' => 'App\\Entity\\Categorie',
        ]);
    }
}
