<?php

namespace ContainerOaviQtZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlatService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Plat' shared autowired service.
     *
     * @return \App\Entity\Plat
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/Plat.php';

        return $container->privates['App\\Entity\\Plat'] = new \App\Entity\Plat();
    }
}
